### ISSUE TITLE
cant load in defold 1.4.8

### ISSUE THREAD

**Issue by blademaster-888** [Dragosha/slasher-prototype#1]
Hi, this build works fine under 1.44 but I can not get it to work under defold 1.4.8. Is there a way to get around it? 
heres the error i get what i try to run the build:

`ERROR:SPINEEXT: Failed to create Spine Model component. This component only supports materials with the Vertex Space property set to 'vertex-space-world'
WARNING:RESOURCE: Unable to create resource: /_generated_7a2914c.spinemodelc: NOT_SUPPORTED
WARNING:RESOURCE: Unable to create resource: /_generated_aa01c74d.goc: NOT_SUPPORTED
ERROR:GAMEOBJECT: Could not instantiate game object from prototype /_generated_aa01c74d.goc.
ERROR:GAMEOBJECT: Child not found: /hero1/herospine
ERROR:GAMEOBJECT: Child not found: /hero1/torchlight
ERROR:GAMEOBJECT: Child not found: /hero1/triggers
WARNING:RESOURCE: Unable to create resource: /main/scene.collectionc: FORMAT_ERROR`

**Comment by jboadas** [comment]
Just downloaded Defold 1.6.2 and it cannot compile too.

**Comment by jboadas** [comment]
Now Defold is 1.6.3, isn't loading too, most error are from spine
`/defold-spine/src/comp_spine_model.cpp
	Line 861: no matching function for call to 'TestFrustumSphere'
  861 |             bool intersect = dmIntersection::TestFrustumSphere(frustum, center_world, radius, true);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

i could try to fix it but i don't own spine
